### ISSUE TITLE
Code Error

### ISSUE THREAD

**Issue by Art0sh** [henrydatei/ShellShockLiveAimbot#2]
I'm getting errors when trying to execute the script.
Windows 10, Python 3.10
shellshock.py:
```
Traceback (most recent call last):
  File "G:\Downloads\ShellShockLiveAimbot-main\ShellShockLiveAimbot-main\shellshock.py", line 2, in <module>
    from pynput.mouse import Listener as MouseListener
ModuleNotFoundError: No module named 'pynput'
```

shellshock2.py:
```
Traceback (most recent call last):
  File "G:\Downloads\ShellShockLiveAimbot-main\ShellShockLiveAimbot-main\shellshock2.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

**Comment by henrydatei** [comment]
You need to install the packages `pynput` and `opencv`. So just run
```
pip install pynput opencv
```
if this doesn't work, try
```
pip3 install pynput opencv
```
